name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Repository'yi Klonlama
      - name: Checkout repo
        uses: actions/checkout@v3

      # Node.js Sürümünü Ayarlama
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Projenize uygun Node.js sürümünü yazın
          cache: 'pnpm'      # pnpm için cache desteği

      # pnpm'i Kurma
      - name: Install pnpm
        run: npm install -g pnpm

      # Bağımlılıkları Yükleme
      - name: Install dependencies
        run: pnpm install

      # Projeyi Build Etme
      - name: Build project
        run: pnpm build

      # Build Çıktısını Artifact Olarak Yükleme
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Artifact İndirme
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      # GitHub Pages'e Deploy Etme
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
